version : "3"

services:
  web:
    image: aglili/fastapiwithnginx:latest
    container_name: web
    ports:
      - "8000:8000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"

  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      # - "443:443"
    #environment:
    #  - CERTBOT_EMAIL = "you@email.com"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
     # - ./certbot/conf:/etc/letsencrypt

    depends_on:
      - web

    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"

    