name: Build, Push, Deploy

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_KEY }}

      - name: Extract metadata (labels, tags, etc.) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: aglili/fastapiwithnginx

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: aglili/fastapiwithnginx:latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ build_and_push ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files via SSH key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "docker-compose.yml, nginx/nginx.conf"
          target: .

      - name: Run docker-compose
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            if docker compose version > /dev/null 2>&1; then
              DOCKER_COMPOSE_CMD="docker compose"
            else
              DOCKER_COMPOSE_CMD="docker-compose"
            fi
            sudo $DOCKER_COMPOSE_CMD down
            if [ "$(sudo docker images -q)" ]; then
              sudo docker rmi -f $(sudo docker images -q)
            else
              echo "No Docker images to remove"
            fi
            sudo $DOCKER_COMPOSE_CMD pull
            sudo $DOCKER_COMPOSE_CMD up -d
